USE QUANLYTHUVIEN;
GO

-- 1. Drop Constraints and FKs
ALTER TABLE TAIKHOAN DROP CONSTRAINT CK_TAIKHOAN_VAITRO;
ALTER TABLE TAIKHOAN DROP CONSTRAINT CK_TAIKHOAN_CHUSOHUU;

DECLARE @fkName NVARCHAR(200);

-- Drop TAIKHOAN FK to NHANVIEN
SELECT @fkName = name FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('TAIKHOAN') AND referenced_object_id = OBJECT_ID('NHANVIEN');
IF @fkName IS NOT NULL EXEC('ALTER TABLE TAIKHOAN DROP CONSTRAINT ' + @fkName);

-- Drop TAIKHOAN FK to DOCGIA
SELECT @fkName = name FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('TAIKHOAN') AND referenced_object_id = OBJECT_ID('DOCGIA');
IF @fkName IS NOT NULL EXEC('ALTER TABLE TAIKHOAN DROP CONSTRAINT ' + @fkName);

-- Drop PHIEUMUON FK to NHANVIEN
SELECT @fkName = name FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('PHIEUMUON') AND referenced_object_id = OBJECT_ID('NHANVIEN');
IF @fkName IS NOT NULL EXEC('ALTER TABLE PHIEUMUON DROP CONSTRAINT ' + @fkName);
GO

-- 2. Alter Tables
ALTER TABLE TAIKHOAN DROP COLUMN MANV, MADG, VAITRO;
ALTER TABLE PHIEUMUON DROP COLUMN MANV;
GO

-- 3. Drop NHANVIEN table
DROP TABLE NHANVIEN;
GO

-- 4. Drop SPs and Views
DROP PROCEDURE IF EXISTS SP_THEMNHANVIEN;
DROP PROCEDURE IF EXISTS SP_SUANHANVIEN;
DROP PROCEDURE IF EXISTS SP_XOANHANVIEN;
DROP PROCEDURE IF EXISTS SP_LAYDANHSACHNHANVIEN;
DROP VIEW IF EXISTS VW_BC_HIEUSUAT_NHANVIEN;
GO

-- 5. Alter SP_LAPPHIEUMUON
CREATE OR ALTER PROCEDURE SP_LAPPHIEUMUON
@MADG CHAR (5), @DSMACS VARCHAR (200), @MAPM CHAR (6) OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
	SET @MAPM = NULL;
	IF NOT EXISTS (SELECT	*
					FROM		DOCGIA
					WHERE	MADG = @MADG)
		BEGIN
			PRINT N'Độc giả không tồn tại.';
			RETURN 0;
		END
	IF NOT EXISTS (SELECT	*
					FROM		STRING_SPLIT (@DSMACS, ',')
					WHERE	LTRIM(RTRIM(value)) <> '')
		BEGIN
			PRINT N'Phiếu mượn phải có ít nhất một cuốn sách.';
			RETURN 0;
		END
	DECLARE @SONGAY AS INT = 14; 
	BEGIN TRY
		BEGIN TRANSACTION;
		DECLARE @MAX AS INT;
		SELECT	@MAX = ISNULL(MAX(CAST (SUBSTRING(MAPM, 3, 4) AS INT)), 0)
		FROM	PHIEUMUON WITH (UPDLOCK, HOLDLOCK);
		SET @MAPM = 'PM' + RIGHT('0000' + CAST (@MAX + 1 AS VARCHAR (4)), 4);
		INSERT	INTO PHIEUMUON (
			MAPM,
			MADG,
			NGAYMUON,
			HANTRA,
			TINHTRANG
		)
		VALUES                 (@MAPM, @MADG, CAST (GETDATE() AS DATE), DATEADD(DAY, @SONGAY, CAST (GETDATE() AS DATE)), N'Đang mượn');
		INSERT	INTO CTPHIEUMUON (
			MAPM,
			MACS
		)
		SELECT	DISTINCT @MAPM,
						LTRIM(RTRIM(value))
		FROM	STRING_SPLIT (@DSMACS, ',')
		WHERE	LTRIM(RTRIM(value)) <> '';
		COMMIT TRANSACTION;
		PRINT N'Lập phiếu mượn ' + @MAPM + N' thành công.';
		RETURN 1;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK;
		SET @MAPM = NULL;
		DECLARE @LOI AS NVARCHAR (4000) = ERROR_MESSAGE();
		RAISERROR (@LOI, 16, 1);
		RETURN 0;
	END CATCH
END
GO

-- 6. Alter SP_LAYDANHSACHPHIEUMUON
CREATE OR ALTER PROCEDURE SP_LAYDANHSACHPHIEUMUON
	@PageNumber INT = 1,
	@PageSize INT = 10
AS
BEGIN
	SET NOCOUNT ON;
	SELECT PM.MAPM, PM.MADG, DG.HOTEN AS TENDG, PM.NGAYMUON, PM.HANTRA, PM.TINHTRANG,
	       CT.MACS, CT.NGAYTRA, CT.TINHTRANGTRA,
	       COUNT(*) OVER() AS TotalRecord
	FROM PHIEUMUON PM
	LEFT JOIN DOCGIA DG ON PM.MADG = DG.MADG
	LEFT JOIN CTPHIEUMUON CT ON PM.MAPM = CT.MAPM
	ORDER BY PM.NGAYMUON DESC, PM.MAPM DESC
	OFFSET (@PageNumber - 1) * @PageSize ROWS
	FETCH NEXT @PageSize ROWS ONLY;
END
GO
